# vim: syntax=yaml
---

name: "Pipeline"

on:

  # GIT PUSH
  push:
    branches:
      - "main"

  # MANUAL WORKFLOW
  workflow_dispatch:
    inputs:
      log_level:
        type: "choice"
        default: "warning"
        required: true
        description: "Log level for debugging the github workflow"
        options:
          - "info"
          - "debug"
          - "warning"

# SETUP PERMISSIONS
permissions:
  actions: "read"
  id-token: "write"
  contents: "read"
  security-events: "write"

# PIPELINE STEPS
jobs:
  build_docker_image:
      name: "🐳 Build Docker Image"
      runs-on: "ubuntu-latest"
      steps:
        # https://github.com/actions/setup-node
        - uses: "actions/setup-node@v3"
          with:
            node-version: 13
        # https://github.com/actions/checkout
        - uses: "actions/checkout@v3"
        # https://github.com/docker/login-action
        # - uses: "docker/login-action@v2"
        #   with:
        #     registry: ""
        # https://github.com/docker/setup-qemu-action
        - uses: "docker/setup-qemu-action@v1"
        # https://github.com/docker/setup-buildx-action
        - uses: "docker/setup-buildx-action@v1"
        # https://github.com/docker/build-push-action
        - uses: "docker/build-push-action@v3"
          with:
            push: false
            # tags: |
            #   ${{ inputs.docker_ecs_registry_name }}:latest
            context: "."
            # build-args: |
            #   jar_name=${{ inputs.app_jar_name }}
